from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
PLAYER=ROOT/'player'
SRC=PLAYER/'src'; SRC.mkdir(parents=True,exist_ok=True)
(PLAYER/'index.html').write_text(r'''<!doctype html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>Voxel Replay — 4D Human</title></head><body><div id="app"><header><div><h1>VOXEL REPLAY</h1><p>3-View Video → Dynamic 3D Human → Free 4th View</p></div><span id="status">READY</span></header><section class="upload"><div class="uploadTitle">UPLOAD 3 SYNCHRONIZED VIDEOS</div><div class="inputs"><label>CAMERA 1<input id="cam0" type="file" accept="video/*"></label><label>CAMERA 2<input id="cam1" type="file" accept="video/*"></label><label>CAMERA 3<input id="cam2" type="file" accept="video/*"></label><button id="build">CREATE 4D HUMAN</button></div><div id="uploadMsg">Use front / side / rear views of the same scene. The 3rd-person reconstruction can then be rotated to view unseen angles.</div></section><main><div id="viewport"></div><div class="controls"><button id="playPause">▶ PLAY</button><input id="timeline" type="range" min="0" max="0" value="0"><span id="timeLabel">0.00 / 0.00 s</span></div><div id="stats">Waiting for reconstruction…</div><div class="help">🖱 Drag = rotate 360° · Wheel = zoom · 0 = reset view</div></main><script type="module" src="/src/main.js"></script></div></body></html>''',encoding='utf-8')
(SRC/'renderer.js').write_text(r'''import * as THREE from "three";
export class VoxelRenderer{
 constructor(container){this.container=container;this.scene=new THREE.Scene();this.scene.background=new THREE.Color(0xf1f5f9);this.camera=new THREE.PerspectiveCamera(42,1,.01,100);this.group=new THREE.Group();this.scene.add(this.group);this.renderer=new THREE.WebGLRenderer({antialias:true});this.renderer.setPixelRatio(Math.min(devicePixelRatio,2));container.appendChild(this.renderer.domElement);this.yaw=.45;this.pitch=.05;this.distance=3.0;this.target=new THREE.Vector3(0,1.05,0);this.drag=false;container.onpointerdown=e=>{this.drag=true;this.lx=e.clientX;this.ly=e.clientY;container.setPointerCapture(e.pointerId)};container.onpointerup=()=>this.drag=false;container.onpointermove=e=>{if(!this.drag)return;this.yaw-=(e.clientX-this.lx)*.008;this.pitch-=(e.clientY-this.ly)*.006;this.pitch=Math.max(-1.15,Math.min(1.15,this.pitch));this.lx=e.clientX;this.ly=e.clientY};container.onwheel=e=>{e.preventDefault();this.distance*=Math.exp(e.deltaY*.001);this.distance=Math.max(.9,Math.min(7,this.distance))};addEventListener('keydown',e=>{if(e.key==='0'){this.yaw=.45;this.pitch=.05;this.distance=3.0}});addEventListener('resize',()=>this.resize());this.resize();this.animate()}
 resize(){let w=Math.max(1,this.container.clientWidth),h=Math.max(1,this.container.clientHeight);this.camera.aspect=w/h;this.camera.updateProjectionMatrix();this.renderer.setSize(w,h,false)}
 setFrame(voxels,header){this.group.clear();let n=Math.floor(voxels.length/6);if(!n)return;let sx=2.5/Math.max(header.grid_x-1,1),sy=2.5/Math.max(header.grid_y-1,1),sz=2.25/Math.max(header.grid_z-1,1),size=Math.max(.026,Math.min(sx,sy,sz)*1.35);let geo=new THREE.SphereGeometry(size*.72,6,4);let mat=new THREE.MeshBasicMaterial({vertexColors:true});let mesh=new THREE.InstancedMesh(geo,mat,n),d=new THREE.Object3D(),c=new THREE.Color();let minX=99,maxX=-99,minY=99,maxY=-99,minZ=99,maxZ=-99;
 for(let i=0;i<n;i++){let x=voxels[i*6],y=voxels[i*6+1],z=voxels[i*6+2];let px=(x/Math.max(header.grid_x-1,1)-.5)*2.5,py=(z/Math.max(header.grid_z-1,1))*2.25,pz=(y/Math.max(header.grid_y-1,1)-.5)*2.5;minX=Math.min(minX,px);maxX=Math.max(maxX,px);minY=Math.min(minY,py);maxY=Math.max(maxY,py);minZ=Math.min(minZ,pz);maxZ=Math.max(maxZ,pz);d.position.set(px,py,pz);d.updateMatrix();mesh.setMatrixAt(i,d.matrix);let r=voxels[i*6+3],g=voxels[i*6+4],b=voxels[i*6+5];if(r+g+b<80){let t=Math.min(1,py/2.25);c.setRGB(.18+.45*t,.55+.3*t,.9-.18*t)}else c.setRGB(r/255,g/255,b/255);mesh.setColorAt(i,c)}mesh.instanceMatrix.needsUpdate;if(mesh.instanceColor)mesh.instanceColor.needsUpdate;this.group.add(mesh);this.target.set((minX+maxX)/2,(minY+maxY)/2,(minZ+maxZ)/2);let h=Math.max(maxY-minY,.5);this.distance=Math.max(1.9,Math.min(3.6,h*1.65))}
 animate(){requestAnimationFrame(()=>this.animate());let cp=Math.cos(this.pitch),sp=Math.sin(this.pitch),cy=Math.cos(this.yaw),sy=Math.sin(this.yaw);this.camera.position.set(this.target.x+this.distance*cp*sy,this.target.y+this.distance*sp,this.target.z+this.distance*cp*cy);this.camera.lookAt(this.target);this.renderer.render(this.scene,this.camera)}}''',encoding='utf-8')
(SRC/'main.js').write_text(r'''import {VoxelRenderer} from './renderer.js';const $=id=>document.getElementById(id),status=$('status'),timeline=$('timeline'),play=$('playPause'),timeLabel=$('timeLabel'),stats=$('stats'),msg=$('uploadMsg');let data,viewer,current=0,playing=false,last=performance.now(),acc=0;
async function decode(){let r=await fetch('/reconstructed_color.v4d?'+Date.now());if(!r.ok)throw Error('V4D file not found');let b=await r.arrayBuffer(),d=new DataView(b),o=4;if(String.fromCharCode(...new Uint8Array(b,0,4))!=='V4D1')throw Error('Invalid V4D');let version=d.getUint16(o,true);o+=2;if(version!==1)throw Error('Unsupported V4D');let h={grid_x:d.getUint16(o,true),grid_y:d.getUint16(o+2,true),grid_z:d.getUint16(o+4,true),frame_count:d.getUint32(o+6,true),fps:d.getFloat32(o+10,true)};o+=18;let f=[];for(let i=0;i<h.frame_count;i++){let t=d.getFloat32(o,true);o+=4;let n=d.getUint32(o,true);o+=4;let v=new Uint8Array(b,o,n*6);o+=n*6;f.push({timestamp:t,voxels:v})}return{header:h,frames:f}}
function show(i){current=Math.max(0,Math.min(data.frames.length-1,i));let f=data.frames[current];viewer.setFrame(f.voxels,data.header);timeline.value=current;timeLabel.textContent=`${f.timestamp.toFixed(2)} / ${data.frames.at(-1).timestamp.toFixed(2)} s`;stats.textContent=`Frame ${current+1}/${data.frames.length} • ${Math.floor(f.voxels.length/6).toLocaleString()} voxels • ${data.header.fps.toFixed(1)} FPS`}
async function load(){try{data=await decode();if(!viewer)viewer=new VoxelRenderer($('viewport'));timeline.max=data.frames.length-1;show(current);status.textContent='4D HUMAN READY'}catch(e){status.textContent='ERROR';console.error(e)}}
play.onclick=()=>{playing=!playing;play.textContent=playing?'⏸ PAUSE':'▶ PLAY'};timeline.oninput=e=>show(+e.target.value);requestAnimationFrame(function tick(now){let dt=now-last;last=now;if(playing&&data){acc+=dt;let iv=1000/data.header.fps;if(acc>=iv){acc=0;show(current+1>=data.frames.length?0:current+1)}}requestAnimationFrame(tick)});
$('build').onclick=async()=>{let fs=['cam0','cam1','cam2'].map(id=>$(id).files[0]);if(fs.some(x=>!x)){msg.textContent='⚠️ Select all 3 videos first.';return}let fd=new FormData();fs.forEach((f,i)=>fd.append(['cam0','cam1','cam2'][i],f));status.textContent='BUILDING…';msg.textContent='⏳ Uploading 3 videos + AI segmentation + 3D reconstruction…';$('build').disabled=true;try{let r=await fetch('http://127.0.0.1:8000/upload',{method:'POST',body:fd}),j=await r.json();if(!j.ok)throw Error(j.error||'Build failed');msg.textContent='✅ 4D HUMAN CREATED — rotate the scene to inspect the generated 4th view.';await load()}catch(e){msg.textContent='❌ '+e.message;console.error(e)}finally{$('build').disabled=false}};
load();''',encoding='utf-8')
(SRC/'style.css').write_text(r'''*{box-sizing:border-box}html,body{margin:0;height:100%;background:#eef2f7;color:#132033;font-family:Arial,sans-serif}#app{height:100vh;display:flex;flex-direction:column}header{padding:13px 22px;background:#07111f;color:white;display:flex;justify-content:space-between;align-items:center}h1{margin:0;font-size:21px;letter-spacing:2px}header p{margin:3px 0 0;color:#9fb2c9;font-size:12px}#status{background:#123b35;color:#8df0bd;padding:7px 11px;border-radius:20px;font-size:12px;font-weight:bold}.upload{padding:12px 18px;background:white;border-bottom:1px solid #ccd5e1}.uploadTitle{font-size:12px;font-weight:bold;margin-bottom:8px;color:#3d536d}.inputs{display:flex;gap:10px;align-items:center}.inputs label{flex:1;font-size:11px;color:#52657a;font-weight:bold}.inputs input{display:block;width:100%;margin-top:5px}.inputs button{padding:11px 16px;border:0;border-radius:8px;background:#1677ff;color:white;font-weight:bold;cursor:pointer;white-space:nowrap}.inputs button:disabled{opacity:.6}#uploadMsg{font-size:12px;color:#64748b;margin-top:8px}main{flex:1;min-height:0;display:flex;flex-direction:column}#viewport{flex:1;min-height:250px;background:#eef2f7}.controls{display:flex;gap:12px;align-items:center;padding:10px 18px;background:#07111f}.controls input{flex:1}.controls button{padding:9px 16px;border:0;border-radius:7px;background:#1a8cff;color:white;font-weight:bold}.controls span,#stats,.help{font-size:12px;color:#b8c7d9}.help,#stats{padding:7px 18px;background:#0c1828}''',encoding='utf-8')
print('UPLOAD UI PATCHED')
